branch-defaults:
  default:
    environment: Udagramapi2-env
environment-defaults:
  Udagramapi-env:
    branch: null
    repository: null
global:
  application_name: udagram-api2
  branch: main
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: Udacity-Project3-Deployment
  sc: git
  workspace_type: Application
